#!/bin/sh

# This file is part of OpenPanel - The Open Source Control Panel
# OpenPanel is free software: you can redistribute it and/or modify it 
# under the terms of the GNU General Public License as published by the Free 
# Software Foundation, using version 3 of the License.
#
# Please note that use of the OpenPanel trademark may be subject to additional 
# restrictions. For more information, please visit the Legal Information 
# section of the OpenPanel website on http://www.openpanel.com/

APP="$1"
if [ -z "$APP" ]; then
  echo "Need application identifier"
  exit 1
fi

PASSWORD="$2"
if [ -z "$PASSWORD" ]; then
  echo "Missing password"
  exit 1
fi

echo "$PASSWORD" | /usr/bin/openapp-"$APP"-passwd || {
  echo "Setting password failed"
  exit 1
}

