#!/bin/sh

# This file is part of OpenPanel - The Open Source Control Panel
# OpenPanel is free software: you can redistribute it and/or modify it 
# under the terms of the GNU General Public License as published by the Free 
# Software Foundation, using version 3 of the License.
#
# Please note that use of the OpenPanel trademark may be subject to additional 
# restrictions. For more information, please visit the Legal Information 
# section of the OpenPanel website on http://www.openpanel.com/

APP="$1"
if [ -z "$APP" ]; then
  echo "Need application identifier"
  exit 1
fi

SCR="$2"
if [ -z "$SCR" ]; then
  echo "Need script identifier"
  exit 1
fi

if [ ! -x /usr/bin/openapp-"$APP"-"$SCR" ]
then
  echo "Script not found"
  exit 1
fi

DATA="$3"
if [ -z "$DATA" ]; then
  /usr/bin/openapp-"$APP"-"$SCR"
  exit 0
else
  echo "$DATA" | /usr/bin/openapp-"$APP"-"$SCR" stdin || {
  echo "Call failed"
  exit 1
}
